# Generated by Django 4.2.7 on 2023-11-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFilme', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('opiniao', models.CharField(max_length=500)),
            ],
        ),
    ]
