# Generated by Django 4.2.7 on 2023-11-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
