# Generated by Django 4.2.7 on 2023-11-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0004_post_author_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
