# Generated by Django 4.2.7 on 2023-11-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePages', '0007_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='sitePages.category'),
        ),
    ]
